SET NAMES utf8;
CREATE DATABASE apple CHARSET utf8;
USE apple;
CREATE TABLE user(
id INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(100) NOT NULL DEFAULT '',
pwd VARCHAR(32) NOT NULL DEFAULT '',
firstName VARCHAR(10) NOT NULL DEFAULT '',
lastName VARCHAR(10) NOT NULL DEFAULT '',
birthday DATETIME NOT NULL DEFAULT 0,
ques1 VARCHAR(20) NOT NULL DEFAULT '',
ans1 VARCHAR(20) NOT NULL DEFAULT '',
ques2 VARCHAR(20) NOT NULL DEFAULT '',
ans2 VARCHAR(20) NOT NULL DEFAULT '',
ques3 VARCHAR(20) NOT NULL DEFAULT '',
ans3 VARCHAR(20) NOT NULL DEFAULT '',
country VARCHAR(20) NOT NULL DEFAULT '',
news INT NOT NULL DEFAULT 0,
itunes INT NOT NULL DEFAULT 0,
regTime DATETIME NOT NULL DEFAULT 0
);
INSERT INTO user VALUES(null,'21456680@qq.com','900814','柳','林海','1990-11-30','你的第一个宠物叫什么名字？','duoduo','你理想工作是什么','程序猿','你购买的第一张专辑是什么','周杰伦','中国',1,1,NOW());